version: "3.3"

services:
        intranetsearchnode:
                build:
                        context: .
                        dockerfile: Dockerfile
                extra_hosts:
                        - "host.docker.internal:host-gateway"
                volumes:
                        - intranetsearchpublic:/home/node/app/public
                        - intranetsearchimages:/home/node/app/image_save_folder
                ports:
                        - "9011:5000"
                env_file:
                        - .env
        # database:
        # # image to fetch from docker hub
        #         image: mcr.microsoft.com/playwright:v1.34.0-jammy
        

volumes:
        intranetsearchpublic:
        intranetsearchimages: